#!/bin/bash
set -e

# This script updates the AUR package for local-brain-bin
# It's intended to be run by GoReleaser after a successful release

PKG_VER=$1
# We get the SHA256 from the checksums.txt generated by goreleaser
CHECKSUM_FILE="dist/checksums.txt"
MAX_RETRIES=5
RETRY_COUNT=0

while [ ! -f "$CHECKSUM_FILE" ] && [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    echo "Waiting for $CHECKSUM_FILE..."
    sleep 2
    RETRY_COUNT=$((RETRY_COUNT + 1))
done

if [ ! -f "$CHECKSUM_FILE" ]; then
    echo "Error: Checksum file not found after retries"
    exit 1
fi

SHA256=$(grep "local-brain_${PKG_VER}_Linux_x86_64.tar.gz" "$CHECKSUM_FILE" | cut -d ' ' -f 1)

if [ -z "$SHA256" ]; then
    echo "Error: Could not find checksum for Linux x86_64 binary in $CHECKSUM_FILE"
    exit 1
fi

# Use a unique directory to avoid conflicts
AUR_DIR=$(mktemp -d dist/aur-repo.XXXXXX)
echo "Using temporary directory: $AUR_DIR"

# Clean up on exit
trap 'rm -rf "$AUR_DIR"' EXIT

# Tell Git exactly which SSH key to use
export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/aur_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new"

git clone ssh://aur@aur.archlinux.org/local-brain-bin.git "$AUR_DIR"

cd "$AUR_DIR"

# Ensure git user is set up for the push in CI
git config user.name "SanderMoon (via GitHub Actions)"
git config user.email "sander.moonemans@proton.me"

# Update PKGBUILD
sed -i "s/^pkgver=.*/pkgver=${PKG_VER}/" PKGBUILD
sed -i "s/^sha256sums=.*/sha256sums=('${SHA256}')/" PKGBUILD

# Update .SRCINFO manually since makepkg is not available on Ubuntu runners
sed -i "s/pkgver = .*/pkgver = ${PKG_VER}/" .SRCINFO
sed -i "s/sha256sums = .*/sha256sums = ${SHA256}/" .SRCINFO
# Update the source URL in .SRCINFO which contains the version twice
sed -i "s|source = .*|source = https://github.com/SanderMoon/local-brain/releases/download/v${PKG_VER}/local-brain_${PKG_VER}_Linux_x86_64.tar.gz|" .SRCINFO

# Use a lock file to ensure only one push happens if called multiple times
LOCKFILE="../../.aur-push.lock"
if ( set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
    trap 'rm -f "$LOCKFILE"; rm -rf "$AUR_DIR"' EXIT
    
    # Commit and push
    if git diff --quiet PKGBUILD .SRCINFO; then
        echo "No changes to commit for AUR"
    else
        git add PKGBUILD .SRCINFO
        git commit -m "Update to v${PKG_VER}"
        git push origin master
    fi
else
    echo "Another instance is already updating the AUR. Skipping."
fi
