#!/bin/bash
set -e

# This script updates the AUR package for local-brain-bin
# It's intended to be run by GoReleaser after a successful release

PKG_VER=$1
# We get the SHA256 from the checksums.txt generated by goreleaser
# local-brain_1.16.0_Linux_x86_64.tar.gz
SHA256=$(grep "local-brain_${PKG_VER}_Linux_x86_64.tar.gz" dist/checksums.txt | cut -d ' ' -f 1)

if [ -z "$SHA256" ]; then
    echo "Error: Could not find checksum for Linux x86_64 binary"
    exit 1
fi

AUR_DIR="dist/aur-repo"
rm -rf "$AUR_DIR"
git clone ssh://aur@aur.archlinux.org/local-brain-bin.git "$AUR_DIR"

cd "$AUR_DIR"

# Update PKGBUILD
sed -i "s/^pkgver=.*/pkgver=${PKG_VER}/" PKGBUILD
sed -i "s/^sha256sums=.*/sha256sums=('${SHA256}')/" PKGBUILD

# Regenerate .SRCINFO
makepkg --printsrcinfo > .SRCINFO

# Commit and push
git add PKGBUILD .SRCINFO
git commit -m "Update to v${PKG_VER}"
# git push origin master
